//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UilDBIscrittiExporter.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/UilDBIscritti.ImportWcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportTrace", Namespace="http://schemas.datacontract.org/2004/07/UilDBIscritti.IntegrationEntities")]
    [System.SerializableAttribute()]
    public partial class ExportTrace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UilDBIscrittiExporter.ServiceReference1.ExprtType ExportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExporterMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExporterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InitialDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrutturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TransactedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UilDBIscrittiExporter.ServiceReference1.WorkerDTO[] WorkersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Errore {
            get {
                return this.ErroreField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroreField, value) != true)) {
                    this.ErroreField = value;
                    this.RaisePropertyChanged("Errore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExportDate {
            get {
                return this.ExportDateField;
            }
            set {
                if ((this.ExportDateField.Equals(value) != true)) {
                    this.ExportDateField = value;
                    this.RaisePropertyChanged("ExportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExportNumber {
            get {
                return this.ExportNumberField;
            }
            set {
                if ((this.ExportNumberField.Equals(value) != true)) {
                    this.ExportNumberField = value;
                    this.RaisePropertyChanged("ExportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UilDBIscrittiExporter.ServiceReference1.ExprtType ExportType {
            get {
                return this.ExportTypeField;
            }
            set {
                if ((this.ExportTypeField.Equals(value) != true)) {
                    this.ExportTypeField = value;
                    this.RaisePropertyChanged("ExportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExporterMail {
            get {
                return this.ExporterMailField;
            }
            set {
                if ((object.ReferenceEquals(this.ExporterMailField, value) != true)) {
                    this.ExporterMailField = value;
                    this.RaisePropertyChanged("ExporterMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExporterName {
            get {
                return this.ExporterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExporterNameField, value) != true)) {
                    this.ExporterNameField = value;
                    this.RaisePropertyChanged("ExporterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitialDate {
            get {
                return this.InitialDateField;
            }
            set {
                if ((this.InitialDateField.Equals(value) != true)) {
                    this.InitialDateField = value;
                    this.RaisePropertyChanged("InitialDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sector {
            get {
                return this.SectorField;
            }
            set {
                if ((object.ReferenceEquals(this.SectorField, value) != true)) {
                    this.SectorField = value;
                    this.RaisePropertyChanged("Sector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Struttura {
            get {
                return this.StrutturaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrutturaField, value) != true)) {
                    this.StrutturaField = value;
                    this.RaisePropertyChanged("Struttura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Transacted {
            get {
                return this.TransactedField;
            }
            set {
                if ((this.TransactedField.Equals(value) != true)) {
                    this.TransactedField = value;
                    this.RaisePropertyChanged("Transacted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UilDBIscrittiExporter.ServiceReference1.WorkerDTO[] Workers {
            get {
                return this.WorkersField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkersField, value) != true)) {
                    this.WorkersField = value;
                    this.RaisePropertyChanged("Workers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExprtType", Namespace="http://schemas.datacontract.org/2004/07/UilDBIscritti.IntegrationEntities")]
    public enum ExprtType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SimpleExport = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProgramExport = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LiberiExport = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerSideExport = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkerDTO", Namespace="http://schemas.datacontract.org/2004/07/UilDBIscritti.IntegrationEntities")]
    [System.SerializableAttribute()]
    public partial class WorkerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentAziendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExistBirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExistLivingPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FiscalcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscrittoAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastModifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LiberoAlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LivingPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LivingProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UilDBIscrittiExporter.ServiceReference1.SubscriptionDTO SubscriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UilDBIscrittiExporter.ServiceReference1.SubscriptionDTO[] SubscriptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthProvince {
            get {
                return this.BirthProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthProvinceField, value) != true)) {
                    this.BirthProvinceField = value;
                    this.RaisePropertyChanged("BirthProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cap {
            get {
                return this.CapField;
            }
            set {
                if ((object.ReferenceEquals(this.CapField, value) != true)) {
                    this.CapField = value;
                    this.RaisePropertyChanged("Cap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentAzienda {
            get {
                return this.CurrentAziendaField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentAziendaField, value) != true)) {
                    this.CurrentAziendaField = value;
                    this.RaisePropertyChanged("CurrentAzienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExistBirthPlace {
            get {
                return this.ExistBirthPlaceField;
            }
            set {
                if ((this.ExistBirthPlaceField.Equals(value) != true)) {
                    this.ExistBirthPlaceField = value;
                    this.RaisePropertyChanged("ExistBirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExistLivingPlace {
            get {
                return this.ExistLivingPlaceField;
            }
            set {
                if ((this.ExistLivingPlaceField.Equals(value) != true)) {
                    this.ExistLivingPlaceField = value;
                    this.RaisePropertyChanged("ExistLivingPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fiscalcode {
            get {
                return this.FiscalcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FiscalcodeField, value) != true)) {
                    this.FiscalcodeField = value;
                    this.RaisePropertyChanged("Fiscalcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscrittoA {
            get {
                return this.IscrittoAField;
            }
            set {
                if ((object.ReferenceEquals(this.IscrittoAField, value) != true)) {
                    this.IscrittoAField = value;
                    this.RaisePropertyChanged("IscrittoA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifier {
            get {
                return this.LastModifierField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifierField, value) != true)) {
                    this.LastModifierField = value;
                    this.RaisePropertyChanged("LastModifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate {
            get {
                return this.LastUpdateField;
            }
            set {
                if ((this.LastUpdateField.Equals(value) != true)) {
                    this.LastUpdateField = value;
                    this.RaisePropertyChanged("LastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LiberoAl {
            get {
                return this.LiberoAlField;
            }
            set {
                if ((this.LiberoAlField.Equals(value) != true)) {
                    this.LiberoAlField = value;
                    this.RaisePropertyChanged("LiberoAl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LivingPlace {
            get {
                return this.LivingPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.LivingPlaceField, value) != true)) {
                    this.LivingPlaceField = value;
                    this.RaisePropertyChanged("LivingPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LivingProvince {
            get {
                return this.LivingProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.LivingProvinceField, value) != true)) {
                    this.LivingProvinceField = value;
                    this.RaisePropertyChanged("LivingProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UilDBIscrittiExporter.ServiceReference1.SubscriptionDTO Subscription {
            get {
                return this.SubscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionField, value) != true)) {
                    this.SubscriptionField = value;
                    this.RaisePropertyChanged("Subscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UilDBIscrittiExporter.ServiceReference1.SubscriptionDTO[] Subscriptions {
            get {
                return this.SubscriptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionsField, value) != true)) {
                    this.SubscriptionsField = value;
                    this.RaisePropertyChanged("Subscriptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionDTO", Namespace="http://schemas.datacontract.org/2004/07/UilDBIscritti.IntegrationEntities")]
    [System.SerializableAttribute()]
    public partial class SubscriptionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FiscalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InitialDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SemesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrutturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contract {
            get {
                return this.ContractField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractField, value) != true)) {
                    this.ContractField = value;
                    this.RaisePropertyChanged("Contract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployCompany {
            get {
                return this.EmployCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployCompanyField, value) != true)) {
                    this.EmployCompanyField = value;
                    this.RaisePropertyChanged("EmployCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FiscalCode {
            get {
                return this.FiscalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FiscalCodeField, value) != true)) {
                    this.FiscalCodeField = value;
                    this.RaisePropertyChanged("FiscalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitialDate {
            get {
                return this.InitialDateField;
            }
            set {
                if ((this.InitialDateField.Equals(value) != true)) {
                    this.InitialDateField = value;
                    this.RaisePropertyChanged("InitialDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quota {
            get {
                return this.QuotaField;
            }
            set {
                if ((this.QuotaField.Equals(value) != true)) {
                    this.QuotaField = value;
                    this.RaisePropertyChanged("Quota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sector {
            get {
                return this.SectorField;
            }
            set {
                if ((object.ReferenceEquals(this.SectorField, value) != true)) {
                    this.SectorField = value;
                    this.RaisePropertyChanged("Sector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Semester {
            get {
                return this.SemesterField;
            }
            set {
                if ((this.SemesterField.Equals(value) != true)) {
                    this.SemesterField = value;
                    this.RaisePropertyChanged("Semester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Struttura {
            get {
                return this.StrutturaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrutturaField, value) != true)) {
                    this.StrutturaField = value;
                    this.RaisePropertyChanged("Struttura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IImportExport")]
    public interface IImportExport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetData", ReplyAction="http://tempuri.org/IImportExport/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetData", ReplyAction="http://tempuri.org/IImportExport/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IImportExport/GetDataUsingDataContractResponse")]
        UilDBIscrittiExporter.ServiceReference1.CompositeType GetDataUsingDataContract(UilDBIscrittiExporter.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IImportExport/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<UilDBIscrittiExporter.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(UilDBIscrittiExporter.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/ImportData", ReplyAction="http://tempuri.org/IImportExport/ImportDataResponse")]
        string ImportData(UilDBIscrittiExporter.ServiceReference1.ExportTrace trace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/ImportData", ReplyAction="http://tempuri.org/IImportExport/ImportDataResponse")]
        System.Threading.Tasks.Task<string> ImportDataAsync(UilDBIscrittiExporter.ServiceReference1.ExportTrace trace);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImportExportChannel : UilDBIscrittiExporter.ServiceReference1.IImportExport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportExportClient : System.ServiceModel.ClientBase<UilDBIscrittiExporter.ServiceReference1.IImportExport>, UilDBIscrittiExporter.ServiceReference1.IImportExport {
        
        public ImportExportClient() {
        }
        
        public ImportExportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportExportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportExportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportExportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public UilDBIscrittiExporter.ServiceReference1.CompositeType GetDataUsingDataContract(UilDBIscrittiExporter.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<UilDBIscrittiExporter.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(UilDBIscrittiExporter.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string ImportData(UilDBIscrittiExporter.ServiceReference1.ExportTrace trace) {
            return base.Channel.ImportData(trace);
        }
        
        public System.Threading.Tasks.Task<string> ImportDataAsync(UilDBIscrittiExporter.ServiceReference1.ExportTrace trace) {
            return base.Channel.ImportDataAsync(trace);
        }
    }
}
