//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UilDBIscrittiExporter.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IImportExport")]
    public interface IImportExport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/ImportData", ReplyAction="http://tempuri.org/IImportExport/ImportDataResponse")]
        string ImportData(UilDBIscritti.IntegrationEntities.ExportTrace trace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/ImportData", ReplyAction="http://tempuri.org/IImportExport/ImportDataResponse")]
        System.Threading.Tasks.Task<string> ImportDataAsync(UilDBIscritti.IntegrationEntities.ExportTrace trace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetCategories", ReplyAction="http://tempuri.org/IImportExport/GetCategoriesResponse")]
        string[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetCategories", ReplyAction="http://tempuri.org/IImportExport/GetCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetTerritori", ReplyAction="http://tempuri.org/IImportExport/GetTerritoriResponse")]
        string[] GetTerritori();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportExport/GetTerritori", ReplyAction="http://tempuri.org/IImportExport/GetTerritoriResponse")]
        System.Threading.Tasks.Task<string[]> GetTerritoriAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImportExportChannel : UilDBIscrittiExporter.ServiceReference1.IImportExport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportExportClient : System.ServiceModel.ClientBase<UilDBIscrittiExporter.ServiceReference1.IImportExport>, UilDBIscrittiExporter.ServiceReference1.IImportExport {
        
        public ImportExportClient() {
        }
        
        public ImportExportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportExportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportExportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportExportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ImportData(UilDBIscritti.IntegrationEntities.ExportTrace trace) {
            return base.Channel.ImportData(trace);
        }
        
        public System.Threading.Tasks.Task<string> ImportDataAsync(UilDBIscritti.IntegrationEntities.ExportTrace trace) {
            return base.Channel.ImportDataAsync(trace);
        }
        
        public string[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public string[] GetTerritori() {
            return base.Channel.GetTerritori();
        }
        
        public System.Threading.Tasks.Task<string[]> GetTerritoriAsync() {
            return base.Channel.GetTerritoriAsync();
        }
    }
}
